basic_words = (
    "apple", "beach", "berry", "black", "blue", "bread", "brick", "brown",
    "brush", "bunny", "candy", "chair", "charm", "cherry", "clean", "clear",
    "cloud", "coast", "coral", "cream", "dance", "dark", "dream", "drink",
    "eagle", "earth", "fairy", "flame", "flower", "forest", "fresh", "frost",
    "fruit", "funny", "ghost", "glass", "green", "grape", "grass", "great",
    "happy", "heart", "honey", "horse", "house", "light", "lemon", "lucky",
    "magic", "mango", "maple", "melon", "merry", "metal", "money", "moon",
    "mouse", "music", "night", "olive", "ocean", "orange", "paint", "paper",
    "peach", "pearl", "piano", "picnic", "pilot", "pink", "planet", "plant",
    "plate", "plain", "plum", "point", "queen", "quick", "quiet", "rabbit",
    "rain", "rainbow", "ready", "river", "robot", "rocky", "rose", "round",
    "royal", "ruby", "salad", "salt", "sandy", "sauce", "school", "shiny",
    "short", "smile", "smoke", "snake", "snow", "soft", "solar", "sound",
    "space", "spark", "speak", "spice", "spider", "spring", "square", "star",
    "stone", "storm", "story", "sugar", "sunny", "sweet", "table", "tiger",
    "toast", "today", "tomato", "tower", "train", "tree", "trend", "trick",
    "truck", "tulip", "turtle", "water", "wave", "wheat", "white", "windy",
    "winter", "wise", "woman", "world", "yellow", "young", "zebra", "alarm",
    "angel", "arrow", "artist", "autumn", "baby", "basket", "beauty", "blanket",
    "bottle", "button", "camera", "carrot", "castle", "circle", "coffee", "cookie",
    "cotton", "cricket", "crown", "crystal", "dinner", "dragon", "drawer", "energy",
    "engine", "family", "farmer", "feather", "field", "finger", "fire", "fish",
    "folder", "friend", "garden", "garlic", "gentle", "ginger", "golden", "guitar",
    "hammer", "hand", "harbor", "helmet", "island", "jacket", "jewel", "kitchen",
    "kitten", "ladder", "lake", "letter", "little", "local", "lunch", "market",
    "morning", "mother", "nature", "pencil", "pepper", "phone", "pillow", "pocket",
    "poetry", "purple", "puzzle", "rocket", "runner", "sailor", "season", "secret",
    "shadow", "silver", "singer", "sketch", "sleepy", "small", "soccer", "summer",
    "sunset", "tablet", "talent", "teacher", "ticket", "travel", "valley", "velvet",
    "violet", "walnut", "warm", "window", "winner"
)